#!/bin/bash

#SBATCH -J Tutorial1            # name of job in queue
#SBATCH -o Sample_job.o%j       # output file (%j appends job name)
#SBATCH -p public               # partition
#SBATCH --qos general           # quality of service
#SBATCH -N 1                    # Number of nodes
#SBATCH -n 16                   # Number of processors
#SBATCH -t 12:00:00             # Wallclock time

### Loading modules
module load amber/16-gen

mpirun -np 16 sander.MPI -O -i polyAT_vac_init_min.in -o polyAT_vac_init_min.out -c polyAT_vac.inpcrd -p polyAT_vac.prmtop -r polyAT_vac_init_min.rst
